// Code generated by protoc-gen-go. DO NOT EDIT.
// source: camdevice-to-image.proto

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	camdevice-to-image.proto

It has these top-level messages:
	Chunk
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Chunk struct {
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
}

func (m *Chunk) Reset()                    { *m = Chunk{} }
func (m *Chunk) String() string            { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()               {}
func (*Chunk) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Chunk) GetChunk() []byte {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func init() {
	proto.RegisterType((*Chunk)(nil), "smartpark.Chunk")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chunker service

type ChunkerClient interface {
	Chunker(ctx context.Context, opts ...grpc.CallOption) (Chunker_ChunkerClient, error)
}

type chunkerClient struct {
	cc *grpc.ClientConn
}

func NewChunkerClient(cc *grpc.ClientConn) ChunkerClient {
	return &chunkerClient{cc}
}

func (c *chunkerClient) Chunker(ctx context.Context, opts ...grpc.CallOption) (Chunker_ChunkerClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chunker_serviceDesc.Streams[0], c.cc, "/smartpark.Chunker/Chunker", opts...)
	if err != nil {
		return nil, err
	}
	x := &chunkerChunkerClient{stream}
	return x, nil
}

type Chunker_ChunkerClient interface {
	Send(*Chunk) error
	Recv() (*google_protobuf.Empty, error)
	grpc.ClientStream
}

type chunkerChunkerClient struct {
	grpc.ClientStream
}

func (x *chunkerChunkerClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chunkerChunkerClient) Recv() (*google_protobuf.Empty, error) {
	m := new(google_protobuf.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chunker service

type ChunkerServer interface {
	Chunker(Chunker_ChunkerServer) error
}

func RegisterChunkerServer(s *grpc.Server, srv ChunkerServer) {
	s.RegisterService(&_Chunker_serviceDesc, srv)
}

func _Chunker_Chunker_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkerServer).Chunker(&chunkerChunkerServer{stream})
}

type Chunker_ChunkerServer interface {
	Send(*google_protobuf.Empty) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type chunkerChunkerServer struct {
	grpc.ServerStream
}

func (x *chunkerChunkerServer) Send(m *google_protobuf.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chunkerChunkerServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chunker_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smartpark.Chunker",
	HandlerType: (*ChunkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chunker",
			Handler:       _Chunker_Chunker_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "camdevice-to-image.proto",
}

func init() { proto.RegisterFile("camdevice-to-image.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x48, 0x4e, 0xcc, 0x4d,
	0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xd5, 0x2d, 0xc9, 0xd7, 0xcd, 0xcc, 0x4d, 0x4c, 0x4f, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0xce, 0x4d, 0x2c, 0x2a, 0x29, 0x48, 0x2c, 0xca, 0x96,
	0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x4b, 0x24, 0x95, 0xa6, 0xe9, 0xa7, 0xe6,
	0x16, 0x94, 0x54, 0x42, 0xd4, 0x29, 0xc9, 0x72, 0xb1, 0x3a, 0x67, 0x94, 0xe6, 0x65, 0x0b, 0x89,
	0x70, 0xb1, 0x26, 0x83, 0x18, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x91, 0x0b,
	0x17, 0x3b, 0x58, 0x3a, 0xb5, 0x48, 0xc8, 0x12, 0xc1, 0x14, 0xd0, 0x83, 0x9b, 0xae, 0x07, 0x16,
	0x93, 0x12, 0xd3, 0x83, 0x58, 0xa2, 0x07, 0xb3, 0x44, 0xcf, 0x15, 0x64, 0x89, 0x12, 0x83, 0x06,
	0xa3, 0x01, 0xa3, 0x93, 0x19, 0x97, 0x54, 0x72, 0x4e, 0x7e, 0x69, 0x8a, 0x5e, 0x62, 0x4e, 0x49,
	0x6a, 0x6e, 0x66, 0x71, 0x49, 0x22, 0x92, 0x01, 0x4e, 0x7c, 0xc1, 0x20, 0x76, 0x40, 0x62, 0x51,
	0x76, 0x00, 0x48, 0x73, 0x00, 0x63, 0x14, 0x1b, 0xd8, 0x94, 0xe2, 0x24, 0x08, 0x6d, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x42, 0xf2, 0x88, 0x1e, 0xe7, 0x00, 0x00, 0x00,
}
